### ISSUE TITLE
decimal Parse - local culture problem

### ISSUE THREAD

**Issue by ldolezel** [Jazous/SDKs-DjiImage#1]
All decimal.Parse (all Parse, also int)in Rdf.cs must include System.Globalization.CultureInfo.InvariantCulture, because if international decimal settings is different (in Czech Republic comma), then parse fails.
decimal.Parse(mc.Value.Split('=')[1].Trim('"').Trim('+'), System.Globalization.CultureInfo.InvariantCulture);

**Comment by Jazous** [comment]
Fixed in v1.4.0，Thanks!
