### ISSUE TITLE
Copy Paste error

### ISSUE THREAD

**Issue by ldolezel** [Jazous/SDKs-DjiImage#2]
https://github.com/Jazous/SDKs-DjiImage/blob/036aaf85264680163a85208020d914167d977f24/SDKs.DjiImage.Net48/Thermals/RJPEG.cs#L592

Probably Copy Paste error:    if (maxy > w) maxy = h;
should be: if (maxy > h) maxy = h;

**Comment by Jazous** [comment]
Fixed in v1.4.1.
