### ISSUE TITLE
mavic-2-enterprise-advanced设备照片解析出错

### ISSUE THREAD

**Issue by leioulin** [Jazous/SDKs-DjiImage#3]
大疆设备：
mavic-2-enterprise-advanced

SDK:
SDKs.DjiImage.Net45  (1.4.2.0) 

.net framework 
4.7.1 

出错的代码行：
 using (var img = RJPEG.FromFile("C:\\DJI_0001_R.JPG"))

错误信息
System.InvalidOperationException:“可为空的对象必须具有一个值。”

**Comment by Jazous** [comment]
Fixed in 1.4.3

**Comment by Jazous** [comment]
Fixed in 1.4.3
